### ISSUE TITLE
Review Submission

### ISSUE THREAD

**Issue by not-xygen** [Dillaayh/dillaayu#1]
### Halo Dilla

Sepertinya ada beberapa `article` typo nih jadi `section` nih, tapi untuk struktur udah oke tinggal dirapihin dan dibaikin yang typo.
Lalu sebenernya ada formatting error nih. Kamu bisa pakai prettier biar tahu dimana errornya. Bisa dipakai untuk baikin yah

Sebagai referensi perbaikin dibawah ini kaya ini yah
```html
<main>
 <div id="content">
  <section id="description">...</section>
  <section id="article">
   <article id="article1">...</article> 
   <article id="article2">...</article> 
   ....
 </section>
  <section></section>
 </div>
 <aside>...</aside>
</main>
```

Kalau sudah diupload ulang di repository ini ya, lalu bisa komen dibawah. Thanks!

**Comment by Dillaayh** [comment]
sudah saya upload ulang kak

**Comment by not-xygen** [comment]
### Halo

Kode struktur kurang tepat, tapi bisa diperbaiki dimana strukturnya seharusnya seperti dibawah yah:
```html
<html>
 <header>...</header>
 <main>
  <div id="content">
   <section id="article">
    <article id="">...</article>
     ...
   </section>
   <section id="form">...</section>
   ...
  </div>
  <aside>...</aside>
 </main>
 <footer>...</footer>
</html>
``` 

Yang lain udah oke, Submission ku approved dan diperbaiki ya good luck untuk pembelajaraan CSSnya
